### ISSUE TITLE
encoding problem crash the script

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#170]
I get this error in the Terminal, and my error.log is empty: 

Traceback (most recent call last):
  File "genabout.py", line 940, in <module>
    main(parser, options, args)
  File "genabout.py", line 861, in main
    formatted_output = gen.format_output(components_list)
  File "genabout.py", line 590, in format_output
    context += item + ': ' + value + '\n'
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9a in position 312: ordinal not in range(128)

the problem was caused by the encoding problem in the copyright statement 

Copyright (c) 1997, 1998, 2001 Kungliga Tekniska Högskolan

Two problems here:
1. The error.log should log what was the problem (if there is a problem).
2. the code should handle this encoding problem.

**Comment by chinyeungli** [comment]
I checked again with the version 2.2.1 and cannot reproduce this issue.
