### ISSUE TITLE
develop branch: about gen does not work.

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#226]
```
(about-code-tool) C:\Users\CYL\git\about-code-tool>about gen input.csv test\
C:\Users\CYL\git\about-code-tool\\bin\about-code   gen input.csv test\
Running about-code-tool version 3.0.0dev
Generating ABOUT files...
Traceback (most recent call last):
  File "C:\Users\CYL\git\about-code-tool\bin\about-code-script.py", line 9, in <module>
    load_entry_point('AboutCode==3.0.0', 'console_scripts', 'about-code')()
  File "C:\Users\CYL\git\about-code-tool\lib\site-packages\click\core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\CYL\git\about-code-tool\lib\site-packages\click\core.py", line 590, in main
    rv = self.invoke(ctx)
  File "C:\Users\CYL\git\about-code-tool\lib\site-packages\click\core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\CYL\git\about-code-tool\lib\site-packages\click\core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\CYL\git\about-code-tool\lib\site-packages\click\core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\CYL\git\about-code-tool\about_code_tool\cmd.py", line 130, in gen
    errors, abouts = about_code_tool.gen.generate(location, output)
  File "C:\Users\CYL\git\about-code-tool\about_code_tool\gen.py", line 182, in generate
    errors, abouts = load_inventory(location, bdir)
  File "C:\Users\CYL\git\about-code-tool\about_code_tool\gen.py", line 99, in load_inventory
    errors.extend(check_duplicated_columns(location))
  File "C:\Users\CYL\git\about-code-tool\about_code_tool\gen.py", line 65, in check_duplicated_columns
    columns = reader.next()
  File "C:\Users\CYL\git\about-code-tool\lib\site-packages\unicodecsv\__init__.py", line 106, in next
    row = self.reader.next()
  File "C:\Users\CYL\git\about-code-tool\lib\codecs.py", line 684, in next
    return self.reader.next()
  File "C:\Users\CYL\git\about-code-tool\lib\codecs.py", line 615, in next
    line = self.readline()
  File "C:\Users\CYL\git\about-code-tool\lib\codecs.py", line 530, in readline
    data = self.read(readsize, firstline=True)
  File "C:\Users\CYL\git\about-code-tool\lib\codecs.py", line 477, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd0 in position 0: invalid continuation byte
```

develop branch: about gen does not work. It yields `UnicodeDecodeError` 
Note that my input doesn't seems to contain any weird characters.

**Comment by chinyeungli** [comment]
Probably my input was corrupted. Saving the same context again with a different file work fine.
