### ISSUE TITLE
Error when input have no non-supported fields

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#230]
Doing genabout.py with NO NON-SUPPORTED fields will yield the following error:

```
AboutCode v2.2.0

Traceback (most recent call last):
 File "genabout.py", line 899, in <module>
   main(parser, options, args)
 File "genabout.py", line 843, in main
   for line in input_list:
UnboundLocalError: local variable 'input_list' referenced before assignment
```

**Comment by chinyeungli** [comment]
Need to write test

**Comment by chinyeungli** [comment]
This fix is about reference the data. no test is needed.
