### ISSUE TITLE
Add support for Python 3

### ISSUE THREAD

**Issue by tdruez** [aboutcode-org/aboutcode-toolkit#280]
A must have for ABOUT files adoption in modern codebase.

**Comment by chinyeungli** [comment]
merged changes to `develop`

**Comment by tdruez** [comment]
Thanks for the merge, but I'm re-opening the issue to add the following:
- Remove hardcoded python2.7 in code
- Add python3 support in documentation
- Add python3 in tests integration
- Add python3 in setup.py

**Comment by tdruez** [comment]
Deleted `280-python3` branch in favor of `291-280-python3-support`

**Comment by tdruez** [comment]
For reference:
```
Running aboutcode-toolkit version 3.0.0
Generating .ABOUT files...
Traceback (most recent call last):
 File "aboutcode-toolkit-280-python3-cleanup/src/attributecode/model.py", line 1485, in valid_api_url
   request = urllib2.Request(api_url)
AttributeError: module 'urllib' has no attribute 'Request'
```

**Comment by tdruez** [comment]
This could have been prevented with the proper (missing at the moment) tests for those functions:
- `api.request_license_data`
- `model.valid_api_url`
- `model.pre_process_and_fetch_license_dict`
- `model.is_valid_url`

**Comment by chinyeungli** [comment]
Thanks. I will update those test functions.

**Comment by chinyeungli** [comment]
@tdruez 
For some reasons, when I run the gen command on my windows machine, it gets
```
Running aboutcode-toolkit version 3.0.0
Generating .ABOUT files...
Traceback (most recent call last):
  File "C:\Users\CYL\git\aboutcode-toolkit\bin\about-code-script.py", line 11, in <module>
    load_entry_point('aboutcode-toolkit', 'console_scripts', 'about-code')()
  File "c:\users\cyl\git\aboutcode-toolkit\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\cyl\git\aboutcode-toolkit\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\cyl\git\aboutcode-toolkit\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\cyl\git\aboutcode-toolkit\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\cyl\git\aboutcode-toolkit\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\cyl\git\aboutcode-toolkit\src\attributecode\cmd.py", line 203, in gen
    errors, abouts = gen.generate(
AttributeError: 'AboutCommand' object has no attribute 'generate'
```

However, it works fine on my Ubuntu VM.

**Comment by tdruez** [comment]
@chinyeungli looks like some name shadow issue.
We import `gen` from `generate` in https://github.com/nexB/aboutcode-toolkit/blob/a0d74fd460928d97ba30543b4b80ab15cd575c44/src/attributecode/cmd.py#L33 then we define a function named `gen` in the same module https://github.com/nexB/aboutcode-toolkit/blob/a0d74fd460928d97ba30543b4b80ab15cd575c44/src/attributecode/cmd.py#L186

**Comment by chinyeungli** [comment]
related issue #297
