### ISSUE TITLE
Failure to check some paths in ScanCode

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/aboutcode-toolkit#350]
On Linux, using the develop branch of ScanCode toolkit, https://github.com/nexB/scancode-toolkit/archive/01899da7f92b7fa62339b176941a75f1bdfe4701.zip I run ./configure then activate the virtualenv.
If I run the bundled aboutcode-toolkit with bin/about check tests/ I get this failure:
```
$ bin/about check tests/
Running aboutcode-toolkit version 3.2.0
Checking ABOUT files...
Traceback (most recent call last):
  File "bin/about", line 11, in <module>
    sys.exit(cli())
  File "/tmp/scancode-toolkit/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/scancode-toolkit/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/tmp/scancode-toolkit/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/scancode-toolkit/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/scancode-toolkit/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/tmp/scancode-toolkit/local/lib/python2.7/site-packages/attributecode/cmd.py", line 417, in check
    errors, abouts = model.collect_inventory(location)
  File "/tmp/scancode-toolkit/local/lib/python2.7/site-packages/attributecode/model.py", line 1269, in collect_inventory
    about_locations = list(util.get_about_locations(input_location))
  File "/tmp/scancode-toolkit/local/lib/python2.7/site-packages/attributecode/util.py", line 212, in get_about_locations
    if is_about_file(loc):
  File "/tmp/scancode-toolkit/local/lib/python2.7/site-packages/attributecode/util.py", line 272, in is_about_file
    return path and path.lower().endswith('.about')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 92: ordinal not in range(128)
```

**Comment by pombredanne** [comment]
This is fixed in https://github.com/nexB/aboutcode-toolkit/tree/361-make-transform-work branch
